[0m22:26:02.350324 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7bcad302d940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7bcad294e690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7bcad3799e80>]}


============================== 22:26:02.356902 | e85d639f-7b68-4101-897b-e5b9c5ac4bf4 ==============================
[0m22:26:02.356902 [info ] [MainThread]: Running with dbt=1.8.7
[0m22:26:02.358080 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/user/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:26:02.377512 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/home/user/.dbt')}
[0m22:26:02.378412 [info ] [MainThread]: Creating dbt configuration folder at 
[0m22:26:16.584250 [debug] [MainThread]: Starter project path: /home/user/projects/sales-pipeline/.env/lib/python3.12/site-packages/dbt/include/starter_project
[0m22:26:16.592587 [info ] [MainThread]: 
Your new dbt project "sales_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:26:16.593737 [info ] [MainThread]: Setting up your profile.
[0m22:27:54.538994 [info ] [MainThread]: Profile sales_pipeline written to /home/user/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m22:27:54.541833 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 112.25341, "process_user_time": 1.813222, "process_kernel_time": 0.313671, "process_mem_max_rss": "106644", "process_in_blocks": "93288", "process_out_blocks": "88"}
[0m22:27:54.543488 [debug] [MainThread]: Command `dbt init` succeeded at 22:27:54.543111 after 112.26 seconds
[0m22:27:54.545003 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7bcad4b51040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7bcad28c9250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7bcad28a69c0>]}
[0m22:27:54.546469 [debug] [MainThread]: Flushing usage events
[0m22:32:39.826182 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc26f101370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc270ab97c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc26f280470>]}


============================== 22:32:39.830912 | c8caf170-95ce-4728-90cc-8066df547f6b ==============================
[0m22:32:39.830912 [info ] [MainThread]: Running with dbt=1.8.7
[0m22:32:39.831736 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/user/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt deps', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m22:32:39.832606 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/user/projects/sales-pipeline/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:32:39.833993 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_wall_clock_time": 0.06773466, "process_user_time": 1.585292, "process_kernel_time": 0.261011, "process_mem_max_rss": "85860", "process_in_blocks": "57008", "process_out_blocks": "24", "command_success": false}
[0m22:32:39.834919 [debug] [MainThread]: Command `dbt deps` failed at 22:32:39.834766 after 0.07 seconds
[0m22:32:39.835546 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc26f0b3890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc26f8ee5d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc26f280470>]}
[0m22:32:39.836165 [debug] [MainThread]: Flushing usage events
[0m22:33:36.124345 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a21c68091f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a21c4fd3290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a21c53558b0>]}


============================== 22:33:36.128056 | 551b7a3d-2ae7-4126-bad0-ddfb51a791c9 ==============================
[0m22:33:36.128056 [info ] [MainThread]: Running with dbt=1.8.7
[0m22:33:36.128729 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/user/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt deps', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:33:36.129483 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/user/projects/sales-pipeline/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:33:36.130459 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_wall_clock_time": 0.057236683, "process_user_time": 1.308163, "process_kernel_time": 0.133016, "process_mem_max_rss": "86416", "process_out_blocks": "8", "command_success": false, "process_in_blocks": "0"}
[0m22:33:36.131134 [debug] [MainThread]: Command `dbt deps` failed at 22:33:36.131026 after 0.06 seconds
[0m22:33:36.131563 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a21c68091f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a21c4d646b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a21c4d65a00>]}
[0m22:33:36.132008 [debug] [MainThread]: Flushing usage events
